### ISSUE TITLE
fatboy Datum

### ISSUE THREAD

**Issue by VolkerSchroeder13** [PIMS-ORG/PIMS#10]
von - auf .
also Datum als 01.05.2023

**Comment by finnbechinka** [comment]
Ich bin mir nicht sicher, was hiermit gemeint ist.  Ich sehe bei Fatboy nirgends ein Datum, welches irgendwo geparst wird.

**Comment by finnbechinka** [comment]
Ah doch in glaube, ich habs gefunden. Der Teil des Codes wirft aber einen Fehler. Sollte aber jetzt behoben sein.
