### ISSUE TITLE
EILT - CD-Vet - product_category bleibt leer

### ISSUE THREAD

**Issue by VolkerSchroeder13** [PIMS-ORG/PIMS#34]
damit keine Kategoriezuordnung möglich

**Comment by finnbechinka** [comment]
Ich glaube [40038b9](https://github.com/PIMS-ORG/PIMS/commit/40038b9219ad436550327d1dcc0cf2369ba440cd) sollte das Problem beheben, aber bin mir nicht 100% sicher, weil ich nicht genau weiß, wo die Kategorien herkommen. Ich nehme mal an das die Manuell erstellt werden/wurden? 

Auf jeden Fall habe ich ein Problem, bei welchem die Selektoren nicht in die DB kommen, behoben und das sollte, wenn ich den Code richtig deute, auch dieses Problem mit beheben.

**Comment by VolkerSchroeder13** [comment]
Beim 1. x scrapen werden die Kategorien gefunden

dann ordne ich die über die PIMS Gui passen zu unseren Kategorien zu

beim 2. Durchlauf werden die Kategoriezuordnungen mit gespeichert

Schieb mal in Master, dann teste ich

Viele Grüße aus Bünde

Dipl.-Ing. Volker Schröder

PetVitalShop
Dipl.-Ing. Volker Schröder
Elsemühlenweg 85
32257 Bünde

Fon:  
+4952237944810

***@***.***
Homepage: www.petvitalshop.de

-----Ursprüngliche Daten-----
Datum: 27.10.2023 09:50:54
Von: Finn ***@***.***>
An: PIMS-ORG/PIMS ***@***.***>
CC: VolkerSchroeder13 ***@***.***>, Author ***@***.***>
Betreff: Re: [PIMS-ORG/PIMS] EILT - CD-Vet - product_category bleibt leer (Issue #34)
Vorgang: T-YE6IRTCLBS-00
