### ISSUE TITLE
EILT - Heilkraft Produkte fehlen

### ISSUE THREAD

**Issue by VolkerSchroeder13** [PIMS-ORG/PIMS#71]
Beispiel:
https://heilkraft.online/arthridonum-h

**Comment by MauriceLe** [comment]
`from db.database import Database
from dotenv import dotenv_values
from datetime import datetime
from PyQt6.QtWidgets import *
import pandas as pd


class Export(QWidget):
    
    def __init__(self):
        super().__init__()
        self.db = Database()
        self.env = dotenv_values("../.env")

        self.grid = QGridLayout()
        self.grid.setContentsMargins(30, 30, 30, 30)
 
        self.option = QListWidget()
        self.option.itemClicked.connect(self.add)
        self.option.addItems(self.db.product_fields())
        
        self.select = QListWidget()
        self.select.itemClicked.connect(self.remove)

        self.save = QPushButton('Profil speichern')
        self.save.clicked.connect(self.save_file)

        self.open = QPushButton('Profil öffnen')
        self.open.clicked.connect(self.open_file)

        self.brand = QComboBox()
        self.brand.addItem('Alle')
        self.brand.addItems(self.db.product_brands())

        self.export = QPushButton('Exportieren')
        self.export.clicked.connect(self.export_file)

        self.grid.addWidget(self.option,    1, 0, 1, 1)
        self.grid.addWidget(self.select,    1, 1, 1, 1)
        self.grid.addWidget(self.save,      2, 0, 1, 1)
        self.grid.addWidget(self.open,      2, 1, 1, 1)
        self.grid.addWidget(self.brand,     3, 0, 1, 1)
        self.grid.addWidget(self.export,    3, 1, 1, 1)

        self.setLayout(self.grid)


    def add(self, item):
        self.select.addItem(item.text())

    def remove(self, item):
        self.select.takeItem(self.select.row(item))

    def save_file(self):
        path = QFileDialog.getSaveFileName(self, 'Speichern', '.txt', 'Text (*.txt)')
        
        try:
            with open(path[0], 'w') as file:
                for item in range(self.select.count()):
                    file.write(self.select.item(item).text() + '\n')
        except: pass

    def open_file(self):
        path = QFileDialog.getOpenFileName(self, 'Öffnen', '.txt', 'Text (*.txt)')
        
        try:
            with open(path[0], 'r') as file:
                items = [ line.strip() for line in file ]
            
            self.select.clear()
            self.select.addItems(items)
        except: pass

    def file(self, path, name, fields, data):
        file = path + name + '.xlsx'

        try:
            excel = None
            
            if fields != []:
                excel = pd.DataFrame(data, columns=fields)
            else:
                excel = pd.DataFrame(data)

            with pd.ExcelWriter(file, engine='xlsxwriter', engine_kwargs={'options': {'encoding': 'utf-8'}}) as writer:
                excel.to_excel(writer, index=False)
        except: pass

    def export_file(self):
        product_fields = [self.select.item(i).text() for i in range(self.select.count())]
        image_fields = self.db.image_fields()
        category_fields = []
        
        products = self.db.products(product_fields)
        categories = self.db.products_categories()
        images = self.db.images()

        if self.brand.currentText() != 'Alle':
            products = self.db.products_by_brand(product_fields, self.brand.currentText())                   
            images = self.db.images_by_brand(self.brand.currentText())
            categories = self.db.products_categories_by_brand(self.brand.currentText())

        date = datetime.today().strftime("%d-%m-%Y_%H-%M")
        
        storage = self.env.get('STORAGE')
        export = self.env.get('EXPORT')

        self.file(storage, date + ' Produkte', product_fields, products)
        self.file(storage, date + ' Kategorien', category_fields, categories)
        self.file(export, 'PIMS-Produkte', product_fields, products)
        self.file(export, 'PIMS-Kategorien', category_fields, categories)
        self.file(export, 'PIMS-Images', image_fields, images)`

**Comment by VolkerSchroeder13** [comment]
Bitte noch mal prüfen
NT100001 fehlt immer noch
