### ISSUE TITLE
Aniforte - Variantenbeschreibung mit bei amount rein

### ISSUE THREAD

**Issue by VolkerSchroeder13** [PIMS-ORG/PIMS#85]
https://www.aniforte.de/products/nassfutter-ziege-pur?variant=44039679279371
Bitte die Variantenbeschreibung "1 x 400 g" oder "6 x 400 g" mit bei amount reinschreiben

oder auch
https://www.aniforte.de/products/zeckenschild-kapseln

egal was da bei Varianten drin steht, immer bei amount rein, dann kann ich das auswerten

**Comment by finnbechinka** [comment]
resolved by 1faecd23e9d2f678cb52cd194f99f9c59bbc2c15
